# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/preferred_classes' do
  # This should return the minimal set of attributes required to create a valid
  # PreferredClass. As you add validations to PreferredClass, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      PreferredClass.create! valid_attributes
      get preferred_classes_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      preferred_class = PreferredClass.create! valid_attributes
      get preferred_class_url(preferred_class)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_preferred_class_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      preferred_class = PreferredClass.create! valid_attributes
      get edit_preferred_class_url(preferred_class)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new PreferredClass' do
        expect do
          post preferred_classes_url, params: { preferred_class: valid_attributes }
        end.to change(PreferredClass, :count).by(1)
      end

      it 'redirects to the created preferred_class' do
        post preferred_classes_url, params: { preferred_class: valid_attributes }
        expect(response).to redirect_to(preferred_class_url(PreferredClass.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new PreferredClass' do
        expect do
          post preferred_classes_url, params: { preferred_class: invalid_attributes }
        end.not_to change(PreferredClass, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post preferred_classes_url, params: { preferred_class: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested preferred_class' do
        preferred_class = PreferredClass.create! valid_attributes
        patch preferred_class_url(preferred_class), params: { preferred_class: new_attributes }
        preferred_class.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the preferred_class' do
        preferred_class = PreferredClass.create! valid_attributes
        patch preferred_class_url(preferred_class), params: { preferred_class: new_attributes }
        preferred_class.reload
        expect(response).to redirect_to(preferred_class_url(preferred_class))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        preferred_class = PreferredClass.create! valid_attributes
        patch preferred_class_url(preferred_class), params: { preferred_class: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested preferred_class' do
      preferred_class = PreferredClass.create! valid_attributes
      expect do
        delete preferred_class_url(preferred_class)
      end.to change(PreferredClass, :count).by(-1)
    end

    it 'redirects to the preferred_classes list' do
      preferred_class = PreferredClass.create! valid_attributes
      delete preferred_class_url(preferred_class)
      expect(response).to redirect_to(preferred_classes_url)
    end
  end
end
