# frozen_string_literal: true

require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/type_profiles' do
  # This should return the minimal set of attributes required to create a valid
  # TypeProfile. As you add validations to TypeProfile, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      TypeProfile.create! valid_attributes
      get type_profiles_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      type_profile = TypeProfile.create! valid_attributes
      get type_profile_url(type_profile)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_type_profile_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      type_profile = TypeProfile.create! valid_attributes
      get edit_type_profile_url(type_profile)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new TypeProfile' do
        expect do
          post type_profiles_url, params: { type_profile: valid_attributes }
        end.to change(TypeProfile, :count).by(1)
      end

      it 'redirects to the created type_profile' do
        post type_profiles_url, params: { type_profile: valid_attributes }
        expect(response).to redirect_to(type_profile_url(TypeProfile.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new TypeProfile' do
        expect do
          post type_profiles_url, params: { type_profile: invalid_attributes }
        end.not_to change(TypeProfile, :count)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post type_profiles_url, params: { type_profile: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested type_profile' do
        type_profile = TypeProfile.create! valid_attributes
        patch type_profile_url(type_profile), params: { type_profile: new_attributes }
        type_profile.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the type_profile' do
        type_profile = TypeProfile.create! valid_attributes
        patch type_profile_url(type_profile), params: { type_profile: new_attributes }
        type_profile.reload
        expect(response).to redirect_to(type_profile_url(type_profile))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        type_profile = TypeProfile.create! valid_attributes
        patch type_profile_url(type_profile), params: { type_profile: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested type_profile' do
      type_profile = TypeProfile.create! valid_attributes
      expect do
        delete type_profile_url(type_profile)
      end.to change(TypeProfile, :count).by(-1)
    end

    it 'redirects to the type_profiles list' do
      type_profile = TypeProfile.create! valid_attributes
      delete type_profile_url(type_profile)
      expect(response).to redirect_to(type_profiles_url)
    end
  end
end
